FLUSH PRIVILEGES;
CREATE USER 'junior'@'%' IDENTIFIED BY '';
CREATE USER 'medior'@'%' IDENTIFIED BY '';
CREATE USER 'senior'@'%' IDENTIFIED BY '';
FLUSH PRIVILEGES;
REVOKE ALL ON *.* FROM 'junior'@'%', 'medior'@'%', 'senior'@'%';
FLUSH PRIVILEGES;
GRANT EXECUTE ON PROCEDURE create_account TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE create_profile TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_login_data TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_login_data TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE validate_email TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_profile TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE change_subscription TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_subscription_definition TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_movies_available_with_definition TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_progress TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE add_to_watchlist TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE remove_from_watchlist TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_subtitle_languages TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_watch_count TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON account_email_password_view TO 'medior'@'%', 'senior'@'%';
GRANT SELECT ON subscription_definition_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON movie_viewer_guide_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON movie_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON movie_watch_count_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON episode_watch_count_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE * TO 'senior'@'%';
FLUSH PRIVILEGES;
GRANT EXECUTE ON PROCEDURE get_daily_income TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_total_income TO 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_full_name TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON account_junior_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON account_medior_view TO 'medior'@'%', 'senior'@'%';
GRANT SELECT ON subscription_record_junior_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON subscription_record_medior_view TO 'medior'@'%', 'senior'@'%';
GRANT SELECT ON subscription_junior_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON language_junior_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_language_title TO 'medior'@'%', 'senior'@'%';
GRANT SELECT ON profile_junior_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_profile_medior TO 'medior'@'%', 'senior'@'%';
GRANT SELECT ON preference_genre_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON preference_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON subtitle_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON movie_junior_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON genre_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON preference_viewer_guide_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON progress_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON episode_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON episode_viewer_guide_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON viewer_guide_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON watchlist_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON definition_type_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON season_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON series_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT SELECT ON movie_viewer_guide_junior_view TO 'junior'@'%', 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_preference_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_subtitle_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_movie_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_episode_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_season_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_genre_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_definition_type_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_season_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE update_viewer_guide_medior TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_movie_count TO 'medior'@'%', 'senior'@'%';
GRANT EXECUTE ON PROCEDURE get_total_income TO 'senior'@'%';
FLUSH PRIVILEGES;